name: magic_extensions
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/gktirkha/magic_extensions
repository: https://github.com/gktirkha/magic_extensions

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
